apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootnode-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaleido
  template:
    metadata:
      labels:
        app: kaleido
    spec:
      initContainers:
      - name: init-data
        image: registry.hub.docker.com/calbrit1/kaleidoproject:jpmorganchase-quorum3
        command: ['sh', '-c', "mv qdatatmp/qdata_0/* qdata/"]
        volumeMounts:
          - mountPath: /qdata
            name: node-pv
      containers:
      - name: bootnode
        args: 
        - bootnode
        - -nodekey
        - /qdata/nodekey
        image: registry.hub.docker.com/calbrit1/kaleidoproject:jpmorganchase-quorum3
        volumeMounts:
          - mountPath: /qdata
            name: node-pv
      volumes:
        - name: node-pv
          persistentVolumeClaim:
            claimName: bootnode-claim
